# Generated by Django 2.2.6 on 2019-10-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='amount',
            field=models.CharField(default=100, max_length=200),
            preserve_default=False,
        ),
    ]
