# Generated by Django 2.2.6 on 2019-10-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_clothes_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('administrator', '管理员'), ('operator', '操作员')], default='操作员', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['create_time'],
            },
        ),
    ]
