# Generated by Django 2.2.6 on 2019-10-26 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Customer')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('操作员', '操作员'), ('管理员', '管理员')], default='操作员', max_length=32),
        ),
        migrations.CreateModel(
            name='OutorderClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Clothes')),
                ('outorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Outorder')),
            ],
        ),
        migrations.AddField(
            model_name='outorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.User'),
        ),
        migrations.CreateModel(
            name='InorderClothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Clothes')),
                ('inorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Inorder')),
            ],
        ),
        migrations.AddField(
            model_name='inorder',
            name='clothes',
            field=models.ManyToManyField(through='common.InorderClothes', to='common.Clothes'),
        ),
        migrations.AddField(
            model_name='inorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.Customer'),
        ),
        migrations.AddField(
            model_name='inorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.User'),
        ),
    ]
