# Generated by Django 2.2.6 on 2019-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191026_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='amount',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(max_length=200),
        ),
    ]
