# Generated by Django 2.2.6 on 2019-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20191026_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inorderclothes',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outorderclothes',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
