# Generated by Django 2.2.6 on 2019-10-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20191026_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.FloatField(max_length=32),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=32),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='sn',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
