# Generated by Django 2.2.6 on 2019-10-28 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20191028_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inorder',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='outorder',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='clothes',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inorder',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='outorder',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modify_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
