# Generated by Django 2.2.6 on 2022-02-12 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20191106_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inorderclothes',
            options={'ordering': ['id'], 'verbose_name': '入库单详情', 'verbose_name_plural': '入库单详情'},
        ),
    ]
